services:
  frontend:
    build:
      context: ./FRontend
      dockerfile: Dockerfile
    container_name: topnet-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - topnet-net
    restart: unless-stopped

  backend:
    build:
      context: ./Backend/TOPNET_PROJECT
      dockerfile: Dockerfile
    container_name: topnet-backend
    ports:
      - "8000:8000"
    networks:
      - topnet-net
    links:
      - db
    # Tip: add restart policy here too if you want the same behavior as frontend
    restart: unless-stopped
  db:
    image: mariadb:latest
    container_name: topnet-db   
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=topnet_db
      - MYSQL_USER=topnet_user
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - topnet-net
    
    

      
volumes:
  db_data:
networks:
  topnet-net:
    driver: bridge