

services:

  frontend:
    build:
      context: ./FRontend
      dockerfile: Dockerfile
    container_name: topnet-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - topnet-net
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build:
      context: ./Backend/TOPNET_PROJECT
      dockerfile: Dockerfile
    container_name: topnet-backend
    ports:
      - "8000:8000"
    networks:
      - topnet-net
    volumes:
      - ./Backend/TOPNET_PROJECT/db.sqlite3:/app/db.sqlite3

networks:
  topnet-net:
    driver: bridge