# Generated by Django 6.0.2 on 2026-02-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='draw_by',
        ),
    ]
