apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
    managed-by: helm
type: Opaque
# b64enc encode automatiquement la valeur en base64
data:
  root-password: {{ .Values.db.rootPassword | b64enc }}
  db-name: {{ .Values.db.name | b64enc }}
  db-user: {{ .Values.db.user | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}                       # 123